Add colored shape page
PhotonVision/photonvision-docs pull request #127
Opened 2021-11-29 17:17 UTC by jasondaming

Closes #114

2021-11-29 18:04 UTC, mdurrani808 requested changes
Thoughts on changing up the pipeline section to add a new page on what a pipeline (called about pipelines) is that talks about the two different types of pipelines and then in the countor grouping section we divide that up into reflective vs. colored shape?  Most of the information you have here could just be copied over to those respective sections.

Would be helpful organization wise and for those who are completely new to vision processing and don't know what a pipeline is. Also makes it more versatile for if we ever decide to add another pipeline type in the future.

2021-11-29 20:07 UTC, jasondaming commented on source/docs/getting-started/pipeline-tuning/colored-shape.rst
> +* Circle Accuracy - This determines how perfect the circle contour must be in order to be considered a circle.  Low values of this (<40) are needed to detect anything but perfect circles.
I like this.  I think "in order" can be removed too right?

2021-11-29 20:10 UTC, jasondaming commented on source/docs/getting-started/pipeline-tuning/colored-shape.rst
> +* Max Canny Threshold - The accumulator threshold for the circle centers at the detection stage. The smaller it is, the more false circles may be detected. Circles, corresponding to the larger accumu
I completely agree.  I just copied what Matt put in the Docs channel on discord.  I haven't been able to play with this because it looks like it has no effect currently.  I can simplify this but I would like to see how this issue effects things: https://github.com/PhotonVision/photonvision/issues/341#issue-1066201555

2021-11-29 20:11 UTC, jasondaming commented on source/docs/getting-started/pipeline-tuning/colored-shape.rst
> +* Shape Simplification - This is the only setting available for polygon, triangle, and quadrilateral target shapes.  This setting also needs to be fairly high (>75) if you are having any problems get
I am not sure how to talk about what it is doing (more than "cleaning up the edges") without launching into something too technical.

2021-11-29 23:47 UTC, mdurrani808 commented on source/docs/getting-started/pipeline-tuning/colored-shape.rst
> +* Circle Accuracy - This determines how perfect the circle contour must be in order to be considered a circle.  Low values of this (<40) are needed to detect anything but perfect circles.
Probably, yeah

2021-12-02 02:31 UTC, mdurrani808 commented on source/docs/getting-started/pipeline-tuning/colored-shape.rst
> +* Shape Simplification - This is the only setting available for polygon, triangle, and quadrilateral target shapes.  This setting also needs to be fairly high (>75) if you are having any problems get
Something about cleaning up the edges will work fine, like increasing the slider will cause PV to search for a simpler shape or something in more refined wording.

2021-12-04 04:03 UTC, mcm001 submitted a review, later dismissed

2021-12-04 04:28 UTC, mdurrani808 commented on source/docs/getting-started/pipeline-tuning/colored-shape.rst
> +* Max Canny Threshold - This sets the amount of change between pixels needed to be considered an edge. The smaller it is, the more false circles may be detected. Circles, corresponding to the larger
I don't know if we've reached the simplification peak  but is it possible to make "circles, corresponding to the larger accumulator values," even simpler to understand? Still don't know what the accumulator phrase means. 

@mcm001 any ideas?

2021-12-04 05:02 UTC, jasondaming commented on source/docs/getting-started/pipeline-tuning/colored-shape.rst
> +* Max Canny Threshold - This sets the amount of change between pixels needed to be considered an edge. The smaller it is, the more false circles may be detected. Circles, corresponding to the larger
I could just remove the word accumulator if that is what is causing the issue?

Maybe something like: "Circles with more points along their ring having high contrast values will be returned first".  If my understanding is correct that is only a small bastardization.

@Bankst thoughts?

2021-12-11 01:39 UTC, mcm001 commented on source/docs/getting-started/pipeline-tuning/colored-shape.rst
> +* Max Canny Threshold - This sets the amount of change between pixels needed to be considered an edge. The smaller it is, the more false circles may be detected. Circles, corresponding to the larger
That sounds better to me? Don't personally totally understand it either

2021-12-13 00:47 UTC, mcm001 approved these changes

2021-12-15 03:49 UTC, merged