Gerth2 hardware json
PhotonVision/photonvision-docs pull request #131
Opened 2021-12-02 01:26 UTC by gerth2

closes https://github.com/PhotonVision/photonvision-docs/issues/120

2021-12-02 01:39 UTC, gerth2 commented
Bonus - ran my spell-checker on other files, and lumped it into one PR, because I'm that organized.

Can split if we care.

2021-12-02 02:50 UTC, mdurrani808 requested changes

2021-12-02 02:50 UTC, mdurrani808 commented on source/conf.py
> +sphinx_tabs_valid_builders = ['epub', 'linkcheck', 'lint']
Assuming that this didn't work, I would delete this for now while we look for a working solution.

2021-12-02 02:50 UTC, mdurrani808 commented on source/docs/hardware/customhardware.rst
> +By default, PhotonVision attempts to make minimal assumptions of the hardware it runs on. However, it may be configured to enable more functionality.
"to enable more functionality including LED control, performance metrics, and brand customization"
Thoughts?

2021-12-02 02:50 UTC, mdurrani808 commented on source/docs/hardware/customhardware.rst
> +.. tabs::
Could you change these tabs to sphinx-design tabs? We will be moving over to these once the relevant PR gets merged.
https://sphinx-design.readthedocs.io/en/furo-theme/tabs.html

2021-12-02 02:50 UTC, mdurrani808 commented on source/docs/hardware/customhardware.rst
> +.. tabs::
See tabs thing

2021-12-02 02:50 UTC, mdurrani808 commented on source/docs/hardware/customhardware.rst
> +.. tabs::
tabs

2021-12-02 02:50 UTC, mdurrani808 commented on source/docs/hardware/customhardware.rst
> +.. tabs::
Tabs

2021-12-02 04:32 UTC, mdurrani808 commented
Also: thanks for the spell checking! All fine in this PR, shouldn't be anything structurally important.

2021-12-04 03:56 UTC, gerth2 commented on source/conf.py
> +sphinx_tabs_valid_builders = ['epub', 'linkcheck', 'lint']
yeeted.

2021-12-04 04:06 UTC, gerth2 commented on source/docs/hardware/customhardware.rst
> +.. tabs::
done, and looks pretty

2021-12-04 04:08 UTC, gerth2 commented on source/docs/hardware/customhardware.rst
> +By default, PhotonVision attempts to make minimal assumptions of the hardware it runs on. However, it may be configured to enable more functionality.
got something close to that which I like

2021-12-04 04:17 UTC, mcm001 approved these changes

2021-12-04 04:22 UTC, mdurrani808 approved these changes

2021-12-04 04:24 UTC, merged