install guides rework and cleanup
PhotonVision/photonvision-docs pull request #182
Opened 2022-09-27 03:01 UTC by gerth2

2022-09-27 03:02 UTC, gerth2 commented
covers https://github.com/PhotonVision/photonvision-docs/issues/130 and part of https://github.com/PhotonVision/photonvision-docs/issues/143

2022-09-27 07:20 UTC, amquake reviewed
Spelling, parity between doc pages

2022-09-27 07:20 UTC, amquake commented on source/docs/getting-started/installation/gloworm.rst
> +Download the latest stable .jar from `the releases page <https://github.com/gloworm-vision/pi-gen/releases>`_, go to the settings tab, and upload the .jar using the Offline Update button.
Offline update jar, not image

2022-09-27 07:20 UTC, amquake commented on source/docs/getting-started/installation/mac-os.rst
> +PhotonVision requires a JDK installed and on the system path. JDK 11 or higher is needed. You may already have this if you have fully installed the FRC toolchain. If not, `download and install it fro
```suggestion
PhotonVision requires a JDK installed and on the system path. JDK 11 or higher is needed. You may already have this if you have fully installed the FRC toolchain. If not, `download and install it from here <https://bell-sw.com/pages/liberica_install_guide-11.0.7/>`_.
```

2022-09-27 07:20 UTC, amquake commented on source/docs/getting-started/installation/mac-os.rst
> +PhotonVision requires a JDK installed and on the system path. JDK 11 or higher is needed. You may already have this if you have fully installed the FRC toolchain. If not, `download and install it fro
Should this match the JDK 11 link from the contribution guide?

2022-09-28 00:35 UTC, mdurrani808 requested changes
Good stuff, thanks for the much needed clean up.

2022-09-28 00:35 UTC, mdurrani808 commented on source/docs/getting-started/installation/linux-pc.rst
> +.. note:: The ``--disable-networking`` flag prevents PhotonVision from automatically changing network settings on your computer.
Last I checked this whole --disable-networking flag never actually existed, would check on this.

2022-09-28 00:35 UTC, mdurrani808 commented on source/docs/getting-started/installation/mac-os.rst
>  .. note:: Due to `cscore <https://github.com/wpilibsuite/allwpilib/tree/main/cscore>`_ restrictions, the PhotonVision server backend cannot run on macOS.
Wording seems confusing here. It says you cant run on macOS in this line but the paragraph above says you can. Would clarify

2022-09-28 00:35 UTC, mdurrani808 commented on source/docs/getting-started/installation/mac-os.rst
> +PhotonVision requires a JDK installed and on the system path. JDK 11 or higher is needed. You may already have this if you have fully installed the FRC toolchain. If not, `download and install it fro
any reason we aren't doing AdoptOpenJDK? That installation experience has always been nicer for our students.

2022-09-28 00:35 UTC, mdurrani808 commented on source/docs/getting-started/installation/mac-os.rst
> +Download the latest stable release of PhotonVision from the `GitHub releases page <https://github.com/PhotonVision/photonvision/releases>`_.
Maybe add the warning for the draft/prerealase stuff as an admonition with better wording. still valuable to include in my opinion

2022-09-28 00:35 UTC, mdurrani808 commented on source/docs/getting-started/installation/other-coprocessors.rst
> +.. note:: The install script has only been tested on Debian/Raspberry Pi OS Buster and Ubuntu Bionic. If any issues arise with your specific OS, please open an issue on our `issues page <https://gith
thoughts on note about support level for other debian based coprocessors?

2022-09-28 00:35 UTC, mdurrani808 commented on source/docs/getting-started/installation/raspberry-pi.rst
> +Download and run `Angry IP Scanner <https://angryip.org/download/#windows>`_ to find PhotonVision/your coprocessor on your network.
As someone who knows little to nothing about networking, this wording is unclear to me. What is finding photonvision on the network like? (ie. look for photonvision.local or something in the 5800 port in the angry ip scanner ui, or something like that). Might be too much, dont know.

2022-09-28 00:35 UTC, mdurrani808 commented on source/docs/getting-started/installation/raspberry-pi.rst
> +Once you find it, set the IP to a desired :ref:`static IP in PhotonVision. <docs/hardware/Settings:Networking>`
I don't want to add in more work for you, but this has lead me to find an infinite loop for instructions that dont exist in our documentation. 

https://docs.photonvision.org/en/latest/docs/getting-started/installation/coprocessor-image.html?highlight=IP#troubleshooting-setting-a-static-ip
Says: set the IP to your static IP in PhotonVision. Instructions for that can be found [here.](https://docs.photonvision.org/en/latest/docs/hardware/Settings.html#networking)

Which leads you to a page that says:
For instructions on how to properly set your static IP, please follow the steps [here](https://docs.photonvision.org/en/latest/docs/getting-started/installation/coprocessor-image.html?highlight=IP#troubleshooting-setting-a-static-ip)

Which then leads you to a page that says: Says: set the IP to your static IP in PhotonVision. Instructions for that can be found [here.](https://docs.photonvision.org/en/latest/docs/hardware/Settings.html#networking)

The instructions for actually setting a static ip don't actually exist, isn't that funny. We should definitely add that up front and obvious within the getting started instructions along with a link to whatever wpi has on it. Along with that, there are two pages related to networking (settings/networking and comp. usage / netowkring), these should be renamed and/or consolidated if possible to reduce confusion.

2022-09-28 00:35 UTC, mdurrani808 commented on source/docs/getting-started/installation/raspberry-pi.rst
> +Download the latest stable .jar from `our releases page <https://github.com/PhotonVision/photonvision/releases>`_, go to the settings tab, and upload the .jar using the Offline Update button.
Note about force restarting as an admonition? Unless we just wanna fix that on our side which would be best

2022-09-28 00:35 UTC, mdurrani808 commented on source/docs/getting-started/installation/snakeyes.rst
> +SnakeEyes Installation
We should probably advertise this more, given that it is the next best thing to a Gloworm. Maybe we do enough already.

2022-09-28 01:48 UTC, gerth2 commented on source/docs/getting-started/installation/mac-os.rst
>  .. note:: Due to `cscore <https://github.com/wpilibsuite/allwpilib/tree/main/cscore>`_ restrictions, the PhotonVision server backend cannot run on macOS.
I might need help on the vocab.

mac OS refers to all apple personal computers, right? Is "Mac PC" an oxymoron or does it apply?

The only goal is to say "works on Mac because java and most of our dependencies build for Mac, but not M1 because most dependencies don't build for M1"

2022-09-28 01:49 UTC, gerth2 commented on source/docs/getting-started/installation/mac-os.rst
>  .. note:: Due to `cscore <https://github.com/wpilibsuite/allwpilib/tree/main/cscore>`_ restrictions, the PhotonVision server backend cannot run on macOS.
Wait actually... is the Note still true? CSCore should support mac.... right?

2022-09-28 01:50 UTC, gerth2 commented on source/docs/getting-started/installation/mac-os.rst
> +PhotonVision requires a JDK installed and on the system path. JDK 11 or higher is needed. You may already have this if you have fully installed the FRC toolchain. If not, `download and install it fro
I think just consistency with what's out there already. Really it should be "whatever wpilib does". I'm hedging though just becuase I've never tried any of the answers recently.

2022-09-28 01:52 UTC, gerth2 commented on source/docs/getting-started/installation/mac-os.rst
> +Download the latest stable release of PhotonVision from the `GitHub releases page <https://github.com/PhotonVision/photonvision/releases>`_.
Possibly. I couldn't remember what sparked the line initially so I figured take it out and see who complained :)

An admonition block seems like a good idea.

2022-09-28 01:54 UTC, gerth2 commented on source/docs/getting-started/installation/other-coprocessors.rst
> +.. note:: The install script has only been tested on Debian/Raspberry Pi OS Buster and Ubuntu Bionic. If any issues arise with your specific OS, please open an issue on our `issues page <https://gith
admonition time! I concur - let folks know there's some "ya gotta know what you're doing" aspect to it.

2022-09-28 01:59 UTC, gerth2 commented on source/docs/getting-started/installation/raspberry-pi.rst
> +Once you find it, set the IP to a desired :ref:`static IP in PhotonVision. <docs/hardware/Settings:Networking>`
![image](https://user-images.githubusercontent.com/4583662/192670226-f5ed60dd-1538-4a45-badf-ed3427c0bfe3.png)

Lolz. I'll see about splitting this back up.

2022-09-28 01:59 UTC, gerth2 commented on source/docs/getting-started/installation/raspberry-pi.rst
> +Download the latest stable .jar from `our releases page <https://github.com/PhotonVision/photonvision/releases>`_, go to the settings tab, and upload the .jar using the Offline Update button.
you shouldn't have to force restart, it shoudl do that automatically? at least on a raspberry pi?

2022-09-28 02:03 UTC, gerth2 commented on source/docs/getting-started/installation/snakeyes.rst
> +SnakeEyes Installation
Possibly could do a reorder? The main reason I think to hold back is to minimize crosstalk with Photonvision doing hardware-specific support or PwF getting pulled into the software support side (beyond just sourcing an image).

2022-09-28 02:52 UTC, gerth2 commented on source/docs/getting-started/installation/linux-pc.rst
> +.. note:: The ``--disable-networking`` flag prevents PhotonVision from automatically changing network settings on your computer.
correct, it is not in source code. Removing.

2022-09-30 19:01 UTC, mdurrani808 commented on source/docs/getting-started/installation/mac-os.rst
>  .. note:: Due to `cscore <https://github.com/wpilibsuite/allwpilib/tree/main/cscore>`_ restrictions, the PhotonVision server backend cannot run on macOS.
I'm not sure if CSCore supports back or not, but Peter would know better. macOS refers to apple computers in my experience, I was just confused because of the seemingly contradictory statements (you can run on a non M1 mac and then PhotonVision cant run on macOS)

2022-09-30 19:01 UTC, mdurrani808 commented on source/docs/getting-started/installation/raspberry-pi.rst
> +Download and run `Angry IP Scanner <https://angryip.org/download/#windows>`_ to find PhotonVision/your coprocessor on your network.
Gotcha, I think a screenshot would be good here.

2022-09-30 19:01 UTC, mdurrani808 commented on source/docs/getting-started/installation/raspberry-pi.rst
> +Download the latest stable .jar from `our releases page <https://github.com/PhotonVision/photonvision/releases>`_, go to the settings tab, and upload the .jar using the Offline Update button.
In the discord some people were talking about how the new UI never updated when doing offline updates. Maybe they were running on PC.

2022-10-08 16:18 UTC, gerth2 commented on source/docs/getting-started/installation/mac-os.rst
>  .. note:: Due to `cscore <https://github.com/wpilibsuite/allwpilib/tree/main/cscore>`_ restrictions, the PhotonVision server backend cannot run on macOS.
I went ahead and hedged. If someone has time to test on macOS and prove the satemetns wrong we can run with that but otherwise.... we'll just leave it vauge and say "there's issues but some works"

2022-10-08 16:52 UTC, gerth2 commented on source/docs/getting-started/installation/raspberry-pi.rst
> +Download and run `Angry IP Scanner <https://angryip.org/download/#windows>`_ to find PhotonVision/your coprocessor on your network.
got a screenshot added

2022-10-09 01:06 UTC, mdurrani808 reviewed
Small spelling error and notes. Good stuff, thanks for all the additions!

2022-10-09 01:06 UTC, mdurrani808 commented on source/docs/getting-started/installation/raspberry-pi.rst
> +Troubleshooting/Setting a Static IP
Ill be making a PR later to reframe this as an actual step to encourage teams to use static ip. Outside the scope of this pr though.

2022-10-09 01:06 UTC, mdurrani808 commented on source/docs/getting-started/installation/linux-pc.rst
> +PhotonVision requires a JDK installed and on the system path. JDK 11 or higher is needed. You may already have this if you have fully installed the FRC toolchain. If not, run the following to install
If I'm a newbie, I don't know what an FRC toolchain is but I do know what WPILib (suggested wording is if you've installed WPILIB) is because I've used it in coding before.

2022-10-09 13:40 UTC, gerth2 commented on source/docs/getting-started/installation/raspberry-pi.rst
> +Insert the flashed microSD card into your Raspberry Pi and boot it up. The first boot may take a few minutes as the Pi expands teh filesystem. Be sure not to unplug during this process.
Seeking: One better spell checker with built-in vsCode support.

2022-10-09 13:48 UTC, gerth2 commented on source/docs/getting-started/installation/linux-pc.rst
> +PhotonVision requires a JDK installed and on the system path. JDK 11 or higher is needed. You may already have this if you have fully installed the FRC toolchain. If not, run the following to install
i like it a lot

2022-10-09 17:08 UTC, mdurrani808 approved these changes
lgtm

2022-10-09 17:08 UTC, merged