Update docs and Java for pose estimator refactoring
PhotonVision/photonvision-docs pull request #262
Opened 2023-01-13 22:19 UTC by agasser

Adjustments for https://github.com/PhotonVision/photonvision/pull/734

2023-01-13 22:24 UTC, mcm001 commented on source/docs/programming/photonlib/robot-pose-estimator.rst
> +            return result;
This probably wont compile -- mismatched types

2023-01-13 23:50 UTC, mdurrani808 requested changes
Thanks for this!

2023-01-13 23:50 UTC, mdurrani808 commented on source/docs/programming/photonlib/robot-pose-estimator.rst
> +      // Construct PhotonPoseEstimator
It would really be best if you just tied this to the actual example using a remote literal include / RLI so it will be udpated in the future (and we know it will compile). See the PhotonLib docs for how to setup an RLI, make sure you tie it to a specific commit.

2023-01-14 04:17 UTC, agasser commented on source/docs/programming/photonlib/robot-pose-estimator.rst
> +      // Construct PhotonPoseEstimator
I was thinking that too, but I was just updating what's there. I can't use a rli until https://github.com/PhotonVision/photonvision/pull/734 gets merged.

2023-01-14 19:43 UTC, mcm001 commented on source/docs/programming/photonlib/robot-pose-estimator.rst
> +      // Construct PhotonPoseEstimator
Merged, so I think we can do RLIs now?

2023-01-15 01:16 UTC, agasser commented on source/docs/programming/photonlib/robot-pose-estimator.rst
> +      // Construct PhotonPoseEstimator
The construction code is different from the example, but I put an RLI in for the `update()` example.

2023-01-17 01:52 UTC, mdurrani808 requested changes

2023-01-17 01:52 UTC, mdurrani808 commented on source/docs/programming/photonlib/robot-pose-estimator.rst
> +PhotonLib includes a ``PhotonPoseEstimator`` class, which allows you to combine the pose data from all tags in view in order to get a field relative pose.
Add note on this page about one photon pose estimator per cam

2023-01-19 02:15 UTC, agasser commented
This should get merged now that the change is released

2023-01-19 02:48 UTC, mdurrani808 approved these changes

2023-01-19 02:48 UTC, merged