Hardware In The Loop Simulation Documentation
PhotonVision/photonvision-docs pull request #270
Opened 2023-01-25 21:56 UTC by brennenputh

This PR adds documentation on how to connect robot code to a PhotonVision instance that is not connected to a robot.  Could maybe use a image or two for where settings are in the GUI?

2023-01-26 02:18 UTC, mdurrani808 requested changes
Been needing this article for a while, much appreciated.

2023-01-26 02:18 UTC, mdurrani808 commented on source/docs/programming/photonlib/hardware-in-the-loop-sim.rst
> +Hardware in the loop simulation is using a physical device, such as a PhotonVision camera, to augment simulation capabilities.
Use simpler language than augment.

2023-01-26 02:18 UTC, mdurrani808 commented on source/docs/programming/photonlib/hardware-in-the-loop-sim.rst
> +This is useful for testing the physical capabilities of a camera, without having to run it on a full robot.
The more pertinent usefulness is to validate code I'd think, or something else rather than just the physical testing of the camera. Most teams probably won't care about just makign sure their camera works before setting up PV proper.

2023-01-26 02:18 UTC, mdurrani808 commented on source/docs/programming/photonlib/hardware-in-the-loop-sim.rst
> +In the settings GUI, turn on "Run NetworkTables Server".
Tell them to go to the settings tab in the sidebar.

2023-01-26 02:18 UTC, mdurrani808 commented on source/docs/programming/photonlib/hardware-in-the-loop-sim.rst
> +      if(isSimulation()) {
isnt it like Robot.isSimulation or something like that? Teams will copy and paste this stuff to their own code base so it should be compileable.

2023-01-26 02:18 UTC, mdurrani808 commented on source/docs/programming/photonlib/hardware-in-the-loop-sim.rst
> +         inst.setServer("photonvision.local");
Add comment saying what they should change this to and when/why

2023-01-27 17:04 UTC, brennenputh commented on source/docs/programming/photonlib/hardware-in-the-loop-sim.rst
> +      if(isSimulation()) {
In TimedRobot you have direct access to `isSimulation()`.  I agree that it would be likely better to change this to `RobotBase.isSimulation()` though to prevent issues with teams putting it somewhere else (like in a trigger).

2023-01-27 17:20 UTC, brennenputh commented on source/docs/programming/photonlib/hardware-in-the-loop-sim.rst
> +Hardware in the loop simulation is using a physical device, such as a PhotonVision camera, to augment simulation capabilities.
Possibly fixed?

2023-01-28 15:32 UTC, mcm001 commented
Awesome! An image or two could be helpful. And the C++ code snippet for sim, I'm not sure if we have that anywhere you can copy from.

2023-01-28 15:57 UTC, mdurrani808 commented
@mcm001 All simulation codeblocks for C++ were removed because of the support being removed. These will hopefully be added in during the rewrite.

2023-01-31 13:02 UTC, brennenputh commented
I believe a C++ block would be appropriate to have here, as hardware-in-the-loop simulation doesn't rely on any simulation support on PhotonVision's side.  I'll try writing something soon and see if I can find a C++ team to test it.

2023-02-04 20:02 UTC, hopeshunta requested changes
Consider explicitly mentioning inst.setServer("localhostl"); for the scenario where a USB camera is connected locally.

2023-02-06 01:07 UTC, brennenputh commented
I believe that is covered enough due to the note to use the address that is used to connect to the UI.

2023-02-06 01:21 UTC, mcm001 commented on source/docs/programming/photonlib/hardware-in-the-loop-sim.rst
> +Hardware in the loop simulation is using a physical device, such as a PhotonVision camera, to enhance simulation capabilities. This is useful for developing and validating code before the camera is a
Maybe "supported co-processor running PhotonVision" instead of "PhotonVision camera"?

2023-02-06 01:21 UTC, mcm001 commented on source/docs/programming/photonlib/hardware-in-the-loop-sim.rst
> +.. note:: This will disable your robot code's internal NT server. Applications connecting to a NT server must be connected to the PhotonVision NT server if this code has been run.
Mention this includes Glass/Shuffleboard/et al

2023-02-06 03:59 UTC, mcm001 approved these changes

2023-02-06 19:07 UTC, mdurrani808 approved these changes

2023-02-06 19:07 UTC, merged