initial docs for sim overhaul [WIP]
PhotonVision/photonvision-docs pull request #283
Opened 2023-08-07 03:08 UTC by jheidegger

Converting some internal documentation about setting up the new simulation environment

Would welcome any and all suggestions and improvements!

still todo

- Transfer over simulation architecture discussion from the deprecated page
- Remove or segment all AdvantageKit references
- Convert Code blocks to Remote Literal Include (will need to coordinate with another PR for this)

2023-08-08 20:14 UTC, mdurrani808 requested changes
Great first article. Took a first pass at this for mainly flow (will do more indepth review later), would be great if we can get @amquake and @mcm001 to review this as well.

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/images/ExampleGeneratedFrame.png
Crop to just the image

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation-deprecated.rst
> +Simulation Support in PhotonLib Deprecated
Depracated in parenthesis

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation-deprecated.rst
> +PhotonLib supports simulation of a Photon Vision camera and processor moving about a field on a robot.
```suggestion
PhotonLib supports simulation of a camera and coprocessor running PhotonVision moving about a field on a robot.
```

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation-deprecated.rst
> +You can use this to help validate your robot code's behavior in simulation without special wrappers or additional hardware.
```suggestion
You can use this to help validate your robot code's behavior in simulation without needing a physical robot.
```

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation-deprecated.rst
> +A ``SimVisionSystem`` represents the camera, coprocessor, and PhotonVision software moving around on the field.
```suggestion
A ``SimVisionSystem`` represents the camera and coprocessor running PhotonVision moving around on the field.
```

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation-deprecated.rst
> +It requires a number of pieces of configuration to accurately simulate your physical setup. Match them to your configuration in PhotonVision, and to your robot's physical dimensions.
Be more specific

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation-deprecated.rst
> +After declaring the system, you should create and add one ``SimVisionTarget`` per target on the field you are attempting to detect.
" per target on the field you are attempting to detect." is ambiguous. is it the field you are trying to detect or the target?

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation-deprecated.rst
> +Robot software which uses PhotonLib to interact with a camera running PhotonVision should work the same as though a real camera was hooked up and active.
Sentence is confusing, and should amke more clear how simulated behavior should match real life camera behavior (you never mention simulatin in this sentence

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation-deprecated.rst
> +Advanced users may wish to directly provide target information based on an existing detailed simulation.
Don't specify advanced users

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
>  You can use this to help validate your robot code's behavior in simulation without special wrappers or additional hardware.
see above

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +It requires a number of pieces of configuration to accurately simulate your physical setup. Match them to your configuration in PhotonVision, and to your robot's physical dimensions.
see above

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +A ``SimVisionSystem`` represents the camera, coprocessor, and PhotonVision software moving around on the field.
see above

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +the new system revolves around the class VisionSystemSim (Note this is different than the official soon to be deprecated SimVision). This class is responsible for updates and coordination of simulate
reword:  (Note this is different than the official soon to be deprecated SimVision)

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +        public class SimPhotonVision extends SubsystemBase{
Should be RLI

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +            new Translation3d(0.0, 0, camHeightOffGround), new Rotation3d(0, camPitch, 0));
see above

2023-08-08 20:14 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +AdvantageKit Logging Results (optional)
Link advantage kit docs or remove this section (dont remember what the consensus was)

2023-08-09 02:46 UTC, jheidegger commented
Just a quick comment the simulation-deprecated was the original documentation that is currently live on the website with the addition of (deprecated) to the title. 

I am totally down to edit it but don't know if that is fully in scope for this PR. Just let me know

2023-08-28 22:32 UTC, mdurrani808 requested changes
@amquake pls review

2023-08-28 22:32 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +.. warning:: This simulation overhaul currently only supports Java.
Reword to: PhotonVision simulation is only supported in Java at this time, but PRs are always welcome or something like that

2023-08-28 22:32 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +A ``VisionSystemSim`` represents the camera, coprocessor, and PhotonVision software moving around on the field. (Note this is different than the official soon to be deprecated SimVision)
different than SimVision (soon to be deprecated) or similar

2023-08-28 22:32 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +The system takes in a series of simulated targets which must be set to the field layout or a custom tag layout. ``VisionSystemSim`` also holds ``PhotonCameraSim`` which must be configured to match th
he system takes in a series of simulated targets which must be set to the field layout or a custom tag layout.

I am confused by this sentence
change to ``VisionSystemSim`` also contains

2023-08-28 22:32 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +then we would like to setup a ``Transform3d`` to represent the position of the simulated camera
make a complete sentence. Add a diagram here as well, people get really confused with this kind of stuff. Stress the importance of accuracy here

2023-08-28 22:32 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +Then create the real camera object if not already defined in the real robot code. then create the simulated camera object which is linked to the real camera to publish the NT4 readings for it. The ``
grammar issues (sentence capitalization, "preset Limelight preset", explain the last two parameters at least whatever % for tag detection means

2023-08-28 22:32 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +Once the simCam has been created it needs to be added to the instance of ``VisionSystemSim`` passing the simulated camera and the ``Transform3d`` representing its location relative to the robot origi
grammar

2023-08-28 22:32 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +Next targets must be added to the vision system. The default targets from the AprilTagFields object are added. This can throw an exception if it fails to load the json so the code must catch and take
grammar (missing commas, say that it must catch the exception)

2023-08-28 22:32 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +Inside the periodic a robot pose must be given to the vision simulation to generate the frames.
Inside the periodic method,

2023-09-20 09:22 UTC, amquake commented
Sorry for the late response.

I started reviewing but squirrel-brained and rewrote the simulation page, which I PRed here: https://github.com/jheidegger/photonvision-docs/pull/1. This links to the updated examples in https://github.com/PhotonVision/photonvision/pull/913, which would mean this pr waits on that. I preferred putting in descriptive code blocks instead of RLIs, hopefully that isn't too much of a maintainability concern. @jheidegger @mdurrani808 Lmk your thoughts

2023-09-22 12:08 UTC, mcm001 commented
We would prefer RLIs when possible

2023-11-22 19:24 UTC, mdurrani808 commented on source/docs/programming/photonlib/simulation.rst
> +      // AprilTagFieldLayout tagLayout = ...;
can you make this an actual atfl

2023-11-22 19:25 UTC, mdurrani808 reviewed
left one comment

2023-11-23 13:23 UTC, gerth2 reviewed
I got through almost everything. Looks real darn solid. Comments are optional/suggestions, feel free to close without resolution.

2023-11-23 13:23 UTC, gerth2 commented on source/docs/programming/photonlib/simulation-deprecated.rst
> +.. attention:: This page details the legacy simulation support. For current Java simulation support, see :doc:`/docs/programming/photonlib/simulation`.
Proposal: replace "legacy" with "pre-2024"

2023-11-23 13:23 UTC, gerth2 commented on source/docs/programming/photonlib/simulation-deprecated.rst
> +.. attention:: This page details the legacy simulation support. For current Java simulation support, see :doc:`/docs/programming/photonlib/simulation`.
Would a call to action make sense here? IE "You will need to migrate to the new simulation support"?

2023-11-23 13:23 UTC, gerth2 commented on source/docs/programming/photonlib/simulation.rst
> +Simulation is a powerful tool teams can use to validate their robot code without needing access to a physical robot. Read more about `simulation in WPILib <https://docs.wpilib.org/en/stable/docs/soft
Reword sugestion:

`Simulation is a powerful tool for validating robot code without access to a physical robot`

Fewer words, same meaning.

2023-11-23 13:23 UTC, gerth2 commented on source/docs/programming/photonlib/simulation.rst
> +   - Full physical camera/world simulation (targets are automatically thresholded)
Suggested change:
* Image Thresholding Process
  * Camera gain, brightness, color skew, noise, etc.

2023-11-23 13:23 UTC, gerth2 commented on source/docs/programming/photonlib/simulation.rst
> +With this approach required information about the camera and target properties is straightforward, and users can easily setup and experiment with PhotonLib in simulation.
Personally, I worry about statements like "X is straightforward" - it can be discouraging if a student is stuck on a problem, sees the line in docs, and then wonders "if it's straightforward, why can't I figure it out?"

I'm assuming the intent of the line is to explain and justify the choice for what is in/out of scope for simulation?

Assuming so.... potential reword:

"This scope was chosen to balance fidelity of the simulation with the ease of setup, in a way that would best-benefit most teams"

2023-11-23 13:23 UTC, gerth2 commented on source/docs/programming/photonlib/simulation.rst
> +A prerequisite for simulating vision frames is knowing where the camera is on the field-- to utilize PhotonVision simulation, you'll need to supply the robot pose periodically. This requires drivetra
Suggested addition: 

Need to supply the _simulated_ robot pose periodically.

2023-11-23 13:23 UTC, gerth2 commented on source/docs/programming/photonlib/simulation.rst
> +A ``VisionSystemSim`` represents the simulated world for the camera, and contains the vision targets it can see. It is constructed with a unique label:
Should the label be globally unique? Or should it match the pipeline name that's in the real camera?

2023-11-23 13:23 UTC, gerth2 commented on source/docs/programming/photonlib/simulation.rst
> +These ``TargetModel`` are paired with a target pose to create a ``VisionTargetSim``. A ``VisionTargetSim`` is added to the ``VisionSystemSim`` to become visible to all of its cameras.
Excellent architecture and API, I'm a fan. Carry on!

2023-11-23 13:23 UTC, gerth2 commented on source/docs/programming/photonlib/simulation.rst
> +If the camera is mounted on a mobile mechanism (like a turret) this transform can be updated later.
Propose changing "updated later" to "updated in a periodic loop".

2023-12-19 01:28 UTC, mdurrani808 approved these changes

2023-12-21 06:56 UTC, mdurrani808 approved these changes

2023-12-21 06:57 UTC, merged