Update networking troubleshooting documentation
PhotonVision/photonvision-docs pull request #296
Opened 2023-11-18 16:48 UTC by philltran

Instructions on flashing image had typo of limelight image instead of Raspberry Pi image.

2023-11-18 21:29 UTC, mcm001 approved these changes

2024-01-01 17:52 UTC, mcm001 requested changes

2024-01-01 17:52 UTC, mcm001 commented on source/docs/troubleshooting/networking-troubleshooting.rst
> -   - Raspberry Pi devices (including Pi 3, Pi 4, CM3 and CM4) should be flashed using the Limelight image (eg, `photonvision-v2023.1.2-linuxarm64-image_RaspberryPi.xz`).
This sentence in general is super confusing. Shouldn't we be telling people to only use the limelight image for Limelight 2/2+, and the regular pi image for normal Pi's?

2024-02-28 04:48 UTC, philltran commented on source/docs/troubleshooting/networking-troubleshooting.rst
> -   - Raspberry Pi devices (including Pi 3, Pi 4, CM3 and CM4) should be flashed using the Limelight image (eg, `photonvision-v2023.1.2-linuxarm64-image_RaspberryPi.xz`).
I added separate line with example for Limelight 2/2+ vs 3. Is that the change you requested or were you thinking a different direction? 

Thanks.

2024-02-28 14:32 UTC, mcm001 submitted a review, later dismissed

2024-03-06 15:55 UTC, mcm001 approved these changes

2024-03-06 15:56 UTC, merged