Added image save docs
PhotonVision/photonvision-docs pull request #48
Opened 2020-11-11 13:44 UTC by gerth2

Added documentation describing the image save command NT entry usage and behavior.

2020-11-11 13:56 UTC, prateekma commented on source/docs/programming/nt-api/nt-api.rst
> +
Will these booleans automatically be set back to false from PhotonVision or will the user have to do that?

2020-11-11 14:03 UTC, gerth2 commented on source/docs/programming/nt-api/nt-api.rst
> +
They get set back 500ms after PhotonVision detects them to be True. User can manually toggle back faster if they want to take images more rapidly than 2/sec .

Worthwhile to add that level of detail?

2020-11-11 14:14 UTC, prateekma commented on source/docs/programming/nt-api/nt-api.rst
> +
Probably not, but I think it's worth mentioning that it gets set back automatically.

2020-11-27 07:19 UTC, mcm001 approved these changes

2020-11-27 07:21 UTC, mcm001 requested changes
@gerth2 wait actually, can we also detail the stuff that was added to photonlib? Specifically takeInputSnapshot and takeOutputSnapshot

2020-11-30 11:23 UTC, mcm001 approved these changes

2020-11-30 11:23 UTC, merged