LimeLight to PhotonVision Conversion Page/Guide
PhotonVision/photonvision-docs pull request #85
Opened 2021-02-14 22:00 UTC by jasondaming

Closes #83

2021-02-14 22:15 UTC, pietroglyph commented
Does the user need change any LED pins for this to work?

2021-02-14 22:21 UTC, Bankst commented
> 
> 
> Does the user need change any LED pins for this to work?

I believe so. @jasondaming can you confirm the pins set in your `hardwareconfig.json`?

2021-02-14 22:22 UTC, pietroglyph commented
And never mind. Just saw your [Discord message](https://discord.com/channels/725836368059826228/725846784131203222/810628336685809704).

2021-02-14 23:50 UTC, jasondaming commented
I actually figured out that I didn't need to change the pins.  I tried chaning them before trying them on the first install but had to do a complete reimage for other reasons and they worked out of the box.

2021-04-04 04:15 UTC, jasondaming commented
@pietroglyph for your review

2021-04-04 04:38 UTC, pietroglyph requested changes

2021-04-04 04:38 UTC, pietroglyph commented on source/docs/getting-started/installation/files/LimeLight2+/hardwareConfig.json
> +{
Remove this file.

2021-04-04 04:38 UTC, pietroglyph commented on source/docs/getting-started/installation/files/LimeLight2/hardwareConfig.json
> +{
Remove this file.

2021-04-04 04:38 UTC, pietroglyph commented on source/docs/getting-started/installation/limelight.rst
> +- PhotonLib making it easier to retrieve data.
Nitpick, but I think it might be more consistent with the tense of the other parts of the page to say

> - Multiple targets that each report their own information
> - Multiple cameras, each of which run an independent pipeline at the same time
> - PhotonLib, which makes it easier to retrieve and do calculations on vision data

2021-04-04 04:38 UTC, pietroglyph commented on source/docs/getting-started/installation/limelight.rst
> +Download the hardwareConfig.json file for the version of your Limelight:
I would emphasize that you need to do this for LED support.

> For full LED support you **must** download a hardware configuration file for your specific Limelight version:

2021-04-04 04:54 UTC, jasondaming commented on source/docs/getting-started/installation/files/LimeLight2+/hardwareConfig.json
> +{
I believe these files need to be here to have something to download right?

2021-04-04 12:58 UTC, jasondaming commented on source/docs/getting-started/installation/files/LimeLight2+/hardwareConfig.json
> +{
Done we actually wanted to keep the Capital versions

2021-04-04 18:49 UTC, Bankst approved these changes

2021-04-04 19:00 UTC, pietroglyph approved these changes

2021-04-04 19:00 UTC, merged